# BEP2 HUland Casino

###
# group: chips
# @name Show balance
GET localhost:8080/chips/balance

###
# group: chips
# @name Make deposit (for development)
POST http://localhost:8080/chips/deposit
Content-Type: application/json

{
  "amount": 1000
}

###
# group: chips
# @name Make withdrawal (for development)
POST http://localhost:8080/chips/withdrawal
Content-Type: application/json

{
  "amount": 1000
}