# BEP2 HUland Casino

###
# group: auth
# @name Register
POST localhost:8080/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "firstName": "Ad",
  "lastName": "Min"
}

###
# group: auth
# @name Login
POST localhost:8080/login
#Accept: application/hal+json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
if (response.status === 200) {
    console.log("testing");
    const authHeader = response.headers.valueOf("Authorization");
    const token = authHeader.substring(7);
    console.log("Setting token: " + token);
    client.global.set("authToken", token);
}

%}

###
# group: chips
# @name Show balance
GET localhost:8080/chips/balance
Authorization: Bearer {{authToken}}

###
# group: chips
# @name Make deposit (for development)
POST http://localhost:8080/chips/deposit
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "amount": 1000
}

###
# group: chips
# @name Make withdrawal (for development)
POST http://localhost:8080/chips/withdrawal
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "amount": 1000
}